version: '3'
services:
 web:
  image: greg78/php7_web
  ports:
   - "80:80"
  volumes:
   - /var/www:/var/www/html
   - /var/www/docker/php7/sites:/etc/apache2/sites-enabled
   - /var/www/docker/php7/php-apache/php-stack.ini:/usr/local/etc/php/conf.d/30-custom.ini
  links:
   - db:db
   - mailhog:mailhog
   - memcached:memcached
  depends_on:
   - db
   - memcached
  deploy:
    replicas: 3
    update_config:
      parallelism: 2
      delay: 10s
    restart_policy:
      condition: on-failure
 memcached:
  image: memcached
  ports:
   - "127.0.0.1:11211:11211"
  deploy:
   placement:
    constraints:
     - node.hostname == leader1
 db:
  image: mysql
  volumes:
   - /var/www/mysql_stack:/var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - TZ=Europe/Paris
  ports:
   - "127.0.0.1:3306:3306"
  deploy:
    replicas: 1
 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: myadmin
  ports :
   - "8080:80"
  environment:
   - PMA_ARBITRARY=1
   - PMA_USER=root
   - PMA_PASSWORD=root
  deploy:
   placement:
    constraints:
     - node.role == manager
  links:
   - db:db
 mailhog:
  image: mailhog/mailhog
  ports: 
   - "1080:8025"
  deploy:
   placement:
    constraints:
     - node.role == manager