web:
 build: ./php-apache
 ports:
  - "80:80"
 volumes:
  - /var/www:/var/www/html
  - /var/www/docker/php5/sites:/etc/apache2/sites-enabled
  - /var/www/docker/php5/php-apache/php.ini:/usr/local/etc/php/conf.d/30-custom.ini
 links:
  - db:db
  - mailhog:mailhost
db:
 image: mysql
 volumes:
  - /var/lib/boot2docker/mysql:/var/lib/mysql
 environment:
  - MYSQL_ROOT_PASSWORD=root
  - TZ=Europe/Paris
 ports:
  - "127.0.0.1:3306:3306"
#mailcatcher:
# restart: always
# image: schickling/mailcatcher
# ports:
#  - "1080:1080"
mailhog:
 image: mailhog/mailhog
 ports: 
  - "1080:8025"
#mongo:
# image: tutum/mongodb
# environment:
#  - MONGODB_PASS=mypass
# ports:
# - "28017:27017"
