web:
 image: armhfbuild/nginx:latest
 ports:
  - "80:80"
 volumes:
  - /var/www:/var/www/html
  - /var/www/Docker/php7fpm/sites:/etc/nginx/conf.d
 links:
  - php
php:
 image: greg78/rpi_php7_fpm
 ports:
  - "80:80"
 volumes:
  - /var/www:/var/www/html
  - /var/www/Docker/php7fpm/php-fpm/php.ini:/usr/local/etc/php/conf.d/30-custom.ini
 links:
  - db:db
db:
 image: hypriot/rpi-mysql
 volumes:
  - /var/www/mysql:/var/lib/mysql
 environment:
  - MYSQL_ROOT_PASSWORD=root
  - TZ=Europe/Paris
  - MAX_ALLOWED_PACKET=32M
 ports:
  - "3306:3306"